steps:
- id: 'Set Context'
  name: 'alpine'
  entrypoint: sh
  args:
    - '-c'
    - |
      echo "********************************************"
      echo "PROJECT           : $PROJECT_ID"
      echo "BRANCH            : $BRANCH_NAME"
      echo "MODE              : $([[ ${_APPLY_CHANGES} = 'true' ]] && echo 'LIVE' || echo 'DRY RUN')"
      echo "********************************************"

# [START Detect changes in specific folders]
- id: 'Detect Changed Folders'
  name: 'gcr.io/cloud-builders/git'
  entrypoint: sh
  args:
    - '-c'
    - |
      echo "********************************************"
      echo "Detecting changes in folders..."
      # Use grep -oE instead of -oP for extended regex support.
      CHANGED_FOLDERS=$(git diff --name-only $COMMIT_SHA^ $COMMIT_SHA | grep -oE 'gcp/[^[:space:]]+' | sort -u)
      echo "Changed folders: $$CHANGED_FOLDERS"
      echo "$$CHANGED_FOLDERS" > /workspace/changed_folders.txt
      cat /workspace/changed_folders.txt
# [END Detect changes in specific folders]

# [START Terraform Init and Plan for Changed Folders]
- id: 'Terraform Plan for Changed Folders'
  name: 'hashicorp/terraform:1.6.6'
  entrypoint: sh
  args:
    - '-c'
    - |
      while read -r folder; do
        echo "********************************************"
        echo "BEGIN: TERRAFORM PLAN FOR $$folder"
        echo "********************************************"
        
        # Initialize Terraform with the proper -chdir flag (equals sign, quoted, and using runtime variable $$folder)
        TF_IN_AUTOMATION=1 terraform -chdir="$$folder" init -upgrade -backend-config="$$folder/init/backend.tfvars" -reconfigure
        
        # Run Terraform plan (using a production var file, adjust the name if needed)
        TF_IN_AUTOMATION=1 terraform -chdir="$$folder" plan -var-file=env/production.tfvars
        
        echo "********************************************"
        echo "END: TERRAFORM PLAN FOR $$folder"
        echo "********************************************"
      done < /workspace/changed_folders.txt
# [END Terraform Init and Plan for Changed Folders]

# [START Terraform Apply for Changed Folders]
- id: 'Terraform Apply for Changed Folders'
  name: 'hashicorp/terraform:1.6.6'
  entrypoint: sh
  args:
    - '-c'
    - |
      if [ "${_APPLY_CHANGES}" = "true" ]; then
        while read -r folder; do
          echo "********************************************"
          echo "BEGIN: TERRAFORM APPLY FOR $$folder"
          echo "********************************************"
          
          # Initialize Terraform for the folder
          TF_IN_AUTOMATION=1 terraform -chdir="$$folder" init -upgrade -backend-config="$$folder/init/backend.tfvars" -reconfigure
          
          # Run Terraform apply
          TF_IN_AUTOMATION=1 terraform -chdir="$$folder" apply -auto-approve -var-file=env/production.tfvars -input=false -no-color
          
          echo "********************************************"
          echo "END: TERRAFORM APPLY FOR $$folder"
          echo "********************************************"
        done < /workspace/changed_folders.txt
      else
        echo "********************************************"
        echo "Skipping apply (DRY RUN)"
        echo "********************************************"
      fi
# [END Terraform Apply for Changed Folders]

timeout: 5400s
options:
  logging: CLOUD_LOGGING_ONLY
