steps:
# [START project-init]
- id: 'Project Init'
  name: gcr.io/cloud-builders/gcloud
  entrypoint: sh
  args:
    - '-c'
    - |
      echo "***********************"
      echo "Project ID        : $_PROJECT_ID"
      echo "Branch            : $_BRANCH_NAME"
      echo "Dry Run           : ${_APPLY_CHANGES}"
      echo "Subfolder         : ${_SUBFOLDER}"
      echo "***********************"
      cd scripts
      chmod +x init.sh
      ./init.sh ${_PROJECT_ID} ${_SUBFOLDER}
# [END project-init]

# [START tf-init]
- id: 'Terraform Init'
  name: 'hashicorp/terraform:1.8.0'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      terraform -chdir=${_SUBFOLDER} init -input=false -no-color -upgrade -backend-config=init/backend.tfvars -reconfigure
# [END tf-init]

# [START tf-plan]
- id: 'Terraform Plan'
  name: 'hashicorp/terraform:1.8.0'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      terraform -chdir=${_SUBFOLDER} plan -out changes.tfplan -var-file=config/variable.tfvars
# [END tf-plan]

# [START tf-apply]
- id: 'Terraform Apply'
  name: 'hashicorp/terraform:1.8.0'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      if [ "${_APPLY_CHANGES}" == "true" ]; then
        terraform -chdir=${_SUBFOLDER} apply -input=false -no-color -auto-approve changes.tfplan
      else
        echo "Skipping apply step (Dry-run mode enabled)"
      fi
# [END tf-apply]

timeout: 5400s
options:
  logging: CLOUD_LOGGING_ONLY
